// Code generated by protoc-gen-bm v0.1, DO NOT EDIT.
// source: hello.proto

/*
Package v1 is a generated blademaster stub package.
This code was generated with kratos/tool/protobuf/protoc-gen-bm v0.1.

package 命名使用 {appid}.{version} 的方式, version 形如 v1, v2 ..

It is generated from these files:
	hello.proto
*/
package v1

import (
	"context"

	bm "github.com/go-kratos/kratos/pkg/net/http/blademaster"
	"github.com/go-kratos/kratos/pkg/net/http/blademaster/binding"
)
import google_protobuf1 "github.com/golang/protobuf/ptypes/empty"

// to suppressed 'imported but not used warning'
var _ *bm.Context
var _ context.Context
var _ binding.StructValidator

var PathHelloSayHello = "/myapp.hello.v1.Hello/SayHello"

// HelloBMServer is the server API for Hello service.
type HelloBMServer interface {
	SayHello(ctx context.Context, req *HelloReq) (resp *google_protobuf1.Empty, err error)
}

var v1HelloSvc HelloBMServer

func helloSayHello(c *bm.Context) {
	p := new(HelloReq)
	if err := c.BindWith(p, binding.Default(c.Request.Method, c.Request.Header.Get("Content-Type"))); err != nil {
		return
	}
	resp, err := v1HelloSvc.SayHello(c, p)
	c.JSON(resp, err)
}

// RegisterHelloBMServer Register the blademaster route
func RegisterHelloBMServer(e *bm.Engine, server HelloBMServer) {
	v1HelloSvc = server
	e.GET("/myapp.hello.v1.Hello/SayHello", helloSayHello)
}
